# Generated by Django 5.1.1 on 2024-10-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth_model',
            name='file_path',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
