# Generated by Django 5.1.1 on 2024-11-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0003_alter_auth_model_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth_model',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
