# Generated by Django 5.1.1 on 2024-11-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0004_auth_model_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth_model',
            name='data_class',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='auth_model',
            name='train_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
