# Generated by Django 5.1.1 on 2024-11-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0005_auth_model_data_class_alter_auth_model_train_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth_model',
            name='keras_type',
            field=models.CharField(default='default_value', max_length=100),
            preserve_default=False,
        ),
    ]
