# Generated by Django 5.1.1 on 2024-11-17 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0007_auth_model_scaler_x_auth_model_scaler_y'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auth_model',
            old_name='scaler_x',
            new_name='scaler_X',
        ),
    ]
